##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [ ]:
import numpy as np

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

#1. Addition of the array
print(a+b)

#2. Substrating of the array
print(a-b)

#3.Multiplication of the array
print(a*b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [ ]:
a = np.array([10,20,30,40])

print(a*5) # sumup operatin every element multipy by 5


[ 50 100 150 200]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [ ]:
import numpy as np
A = np.array([[10,20,30],
             [40,50,60]])
B = np.array([40,50,60])
print(A+B)

[[ 50  70  90]
 [ 80 100 120]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [ ]:
# Basic Statiscal operation perform
import numpy as np

arr = np.array([4,78,34,100,56])
#1.Sum
print(f"Sum is: {arr.sum()}")
#2.Mean
print(f"Mean(Average) is: {arr.mean()}")
#3.Min
print(f"Min is: {arr.min()}")
#4.Max
print(f"Max is: {arr.max()}")

#5.Standard deviation
print(f"Standard Deviation: {arr.std()}")

#6.Varaince
print(f"Varaince:{arr.var()}")

Sum is: 272
Mean(Average) is: 54.4
Min is: 4
Max is: 100
Standard Deviation: 33.452055243288115
Varaince:1119.04


You can also do the axis based operations row-Wise and Colum-wise

In [ ]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f'Sum of all: {data.sum()}')
#axis= 0 -> Columns
#axis= 1 -> rows

print(f'Sum of cloumns: {np.sum(data,axis=0)}') # addition of columns

print(f'Sum of rows: {np.sum(data,axis=1)}') # addition of rows

Sum of all: 45
Sum of cloumns: [12 15 18]
Sum of rows: [ 6 15 24]
