##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60]) # use for fancy indexing pick elements at postion 0,2,4
arr[[0,2,4]]


array([10, 30, 50])

You can do this fancy indexing in 2D Matrix aswell

##Conditional Selection
Find values based on conditions or replace them.

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [ ]:
# Aam zindegi
import numpy as np
array = np.array([2,10,56,1,54])
print(np.sort(array))


index = np.argsort(array)
print(index)



[ 1  2 10 54 56]
[3 0 1 4 2]


In [ ]:
# Matrix sort
matrix = np.array([[4,3,12],[14,10,15]])
#1.Row wise sort(axis = 1)
np.sort(matrix, axis=1)

#2. column Wise Sort(axis=0)
np.sort(matrix,axis=0)

#3. Sort Complete Matrix
np.sort(matrix)

array([[ 3,  4, 12],
       [10, 14, 15]])

##Concatenation & Stacking

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concatenate([a,b]) # use for add


array([1, 2, 3, 4, 5, 6])

Vertical & Horizontal Stacking

In [ ]:
A = np.array([[1,2],[4,5]])
B = np.array([[7,8],[10,11]])

#Vertical Stacking
np.vstack([A,B])

#Horizontal Stacking
np.hstack([A,B])




array([[ 1,  2,  7,  8],
       [ 4,  5, 10, 11]])