# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [15]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [16]:
import numpy as np
l = [10,20,30,40,50] # 1D array
array = np.array(l)
print(array)



[10 20 30 40 50]


Lets create a matrix using list

In [17]:
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]
matrix = np.array(a)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now lets see how matlix looks like using numpy arrays

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [18]:
# np.zeros for 1D
np.zeros(4)


array([0., 0., 0., 0.])

In [19]:
# np.zeros for matrix
# Rows and column
np.zeros([3,4])






array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
# np.ones for 1D
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
# np.ones for matrix
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
# np.full for creating own...
np.full(5,7)

array([7, 7, 7, 7, 7])

In [23]:
# np.full for matrix
np.full([3,3],7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [24]:
# np.arrange() for 1D
arr = np.arange(0,10,2) # using(start,stop,steps)
arr


array([0, 2, 4, 6, 8])

In [25]:
# np.linspace() start =0 , stop = 1, value = 5
np.linspace(0,1,5)



array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
# np.eye() Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
# np.random.rand() # rows,columns
np.random.rand(2,3)

array([[0.0869865 , 0.24633068, 0.42253562],
       [0.45053385, 0.77088574, 0.86951819]])

In [28]:
# np.random.randint(start,stop,(rows,columns))
np.random.randint(1,20,(3,3))
#""" randint :- 1 se 20 ke bech ki random value se matrix create karega """

array([[10, 18,  6],
       [18, 15, 12],
       [ 1, 17,  9]], dtype=int32)

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution